version = 0.1
[default.deploy.parameters]
stack_name = "handkai-backend"
resolve_s3 = true
s3_prefix = "handkai-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HandKAIFunction=037112252821.dkr.ecr.us-east-1.amazonaws.com/handkaibackenda4a7cb78/handkaifunction07361656repo"]
