AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  handkai-backend
  SAM template for handkai

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
  HandKAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        GatewayRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SimpleAppApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  HandKAIFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt HandKAIFunction.Arn
  HandKAIFunctionIamRole:
    Description: "Implicit IAM Role created HAndKAi"
    Value: !GetAtt HandKAIFunctionRole.Arn